### ISSUE TITLE
Error when attempting to get PGE stock

### ISSUE THREAD

**Issue by shnopy** [gadicc/node-yahoo-finance2#154]
# Validation Error

## Minimal Reproduction
- `await yahooFinance.quoteSummary("PGE");`

## Symbol(s) that it happened for
- PGE 

## Error Message
```
The following result did not validate with schema: #/definitions/QuoteSummaryResult
[
  {
    instancePath: '/price/shortName',
    schemaPath: '#/definitions/Price/properties/shortName/type',
    keyword: 'type',
    params: { type: 'string' },
    message: 'must be string',
    data: null
  }
]
```

## Environment
Browser or Node: `node`
Node version (if applicable): 16.0.0
Npm version: 7.6.0
Browser verion (if applicable):
Library version (e.g. `1.10.1`): 1.10.4

**Comment by PythonCreator27** [comment]
Unable to recreate this error. I tried to recreate with the CLI, then using node 14 and a script, and then node 16 and the same script. No validation error came. @shnopy Can you please try to run this again? Maybe it was a momentary thing?

**Comment by shnopy** [comment]
I did try to run it again, I didn't get the message. I do however get an error that `summeryDetail.dayHigh` does not exist when running that

**Comment by PythonCreator27** [comment]
As far as I can tell, the error you get just states that the `dayHigh` property is undefined (and you can't access things on undefined) since you are using a property that may or may not exist (in this case, it does not exist): https://github.com/gadicc/node-yahoo-finance2/blob/00ff24840cb807fb2c0677b34e362e22da6fec79/src/modules/quoteSummary-iface.ts#L748 (In TypeScript, `?` means that it is optional). The error that you get has nothing to do with this library.


If you think that this does seem to have to do with the library, can you please post a bigger reproduction? Maybe a JSFiddle or CodeSandbox.

**Comment by PythonCreator27** [comment]
@shnopy Are you still getting this error?

**Comment by shnopy** [comment]
I'm not, I added a few checks to my script and haven't run into any issues since
