### ISSUE TITLE
Multiple default exports defined in modules + wrong return type

### ISSUE THREAD

**Issue by pudgereyem** [gadicc/node-yahoo-finance2#21]
## Issue

There are multiple default exports defined for the various modules, see below:

1. [`search`](https://github.com/gadicc/node-yahoo-finance2/blob/devel/src/modules/search.ts#L91-L110)
2. [`quoteSummary`](https://github.com/gadicc/node-yahoo-finance2/blob/devel/src/modules/quoteSummary.ts#L94-L113)
3. [`quote`](https://github.com/gadicc/node-yahoo-finance2/blob/devel/src/modules/quote.ts#L113-L139)
4. [`historical`](https://github.com/gadicc/node-yahoo-finance2/blob/devel/src/modules/historical.ts#L34-L53)
5. [`autoc`](https://github.com/gadicc/node-yahoo-finance2/blob/devel/src/modules/autoc.ts#L32-L51)

I'm not sure if this is something intentional? Most of it was added in https://github.com/gadicc/node-yahoo-finance2/commit/dc199b50d46dae26222ccf75bc5efa2c8eff7dcc

I noticed this because I saw that the return type for `search` was changed to `Promise<any>` from `Promise<SearchResult>`, which caused my app to fail since I didn't get the `SearchResult` type.

## Proposed solution

1. Remove all the duplicate default exports for the files above
2. Make sure that the return type is correctly set

**Comment by pudgereyem** [comment]
@gadicc I'm more than happy to create a PR for this! Just wanted to check if this was something intentional first.

**Comment by gadicc** [comment]
Hi thanks, sorry, I only just opened my email and you've already done the PR.  It is intentional :sweat_smile, it's the function overloading for different arguments.  If you specify `{ validateResult: false }` we have to let typescript know that it's not getting a typesafe result anymore, but `any`.  That's super important because we rely on typescript to confirm that our code is typesafe, so without validation it needs to enforce all the manual checks on any data we use.

You'll see the difference as soon as you change the option, e.g.  if you have

```
const result = await yahooFinance.something('AAPL', {}, { validateResult: XXX };
```

If you mouseover `result` when `XXX=true` it will be a `SomethingResult` but if you change it to `XXX=false` and mouseover `result` you'll see it changes to `any`.

You can leave this issue open and I'll make this clearer in the docs.  I'm out of time today though but will check back in tomorrow.

**Comment by gadicc** [comment]
PS same for the other way too:

```js
let result : any;
try {
  // result is a SearchResult
  result = await yahooFinance.search('AAPL');
} catch (error) {
  // result is any
  result = error.result
}
```

because we're not sure of it's type anymore.

**Comment by pudgereyem** [comment]
@gadicc, ahh I see now. So essentially for all different modules you are exporting three variants of the function:

1. Where `moduleOptions.validateResult` is set to `false` (Will return `Promise<any>`)
2. Where `moduleOptions.validateResult` is set to `true` (Will return `Promise<ResponseType>`)
3. Where `moduleOptions.validateResult` is a `boolean` (Will return `Promise<any>`)

However, since `validateResult` is `true` by default, shouldn't it return the ResponseType in that case? The default for [`search`](https://github.com/gadicc/node-yahoo-finance2/blob/devel/src/modules/search.ts#L110) is `any` but the default for [`quoteSummary`](https://github.com/gadicc/node-yahoo-finance2/blob/devel/src/modules/quoteSummary.ts#L113) is `QuoteSummaryResult`.

**Comment by gadicc** [comment]
> However, since `validateResult` is `true` by default, shouldn't it return the ResponseType in that case? The default for [`search`](https://github.com/gadicc/node-yahoo-finance2/blob/devel/src/modules/search.ts#L110) is `any` but the default for [`quoteSummary`](https://github.com/gadicc/node-yahoo-finance2/blob/devel/src/modules/quoteSummary.ts#L113) is `QuoteSummaryResult`.

You're absolutely right.

**Comment by gadicc** [comment]
> @gadicc, ahh I see now. So essentially for all different modules you are exporting three variants of the function:
> 
> 1. Where `moduleOptions.validateResult` is set to `false` (Will return `Promise<any>`)
> 2. Where `moduleOptions.validateResult` is set to `true` (Will return `Promise<ResponseType>`)
> 3. Where `moduleOptions.validateResult` is a `boolean` (Will return `Promise<any>`)

There's actually only 1 function, your (3) above.  The first two are the overloads (alternative function signatures).  So (3) needs to accept the signatures for both (1) and (2) and contains the actual code.  Typescript compiler will go through all signatures in order to pick the first one that matches (that's how this bug came up, because the order was wrong, they should move in increasing specificy).

Not sure how well I explained that but there's more info at https://www.typescriptlang.org/docs/handbook/functions.html#overloads.

**Comment by gadicc** [comment]
Oops I wanted this open until I improved the docs.

**Comment by pudgereyem** [comment]
Morning @gadicc, you explained it very well! I read the official documentation just now as well. Thanks!

**Comment by gadicc** [comment]
You're too kind, thanks :grin:

I have meetings on and off all day today but should be around here and there.
