### ISSUE TITLE
 yarn schema fails on Windows

### ISSUE THREAD

**Issue by Sciguymjm** [gadicc/node-yahoo-finance2#212]
# Bug Report
`yarn schema`/`npm run schema` fails on Windows
## Describe the bug
`yarn schema` fails on Windows due to use of single quotes in command.
## Minimal Reproduction

Run `yarn schema` on Windows. Fails with:
```
Error: No root type "'*'" found
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (file:///node-yahoo-finance2/bin/schema-tweak.js:13:24)
    at Socket.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
error Command failed with exit code 1.

```
due to use of `'*'` in command, as well as other single quotes.
## Environment
Browser or Node: node
Node version (if applicable): 
Npm version: 14.17.0
Browser verion (if applicable):
Library version (e.g. `1.10.1`): 1.13.1

## Additional Context
Workaround: copy command as follows: `ts-json-schema-generator -f tsconfig.json -p "src/{modules/**/*.ts,lib/options.ts}" -t "*" | node bin/schema-tweak.js > schema.json`

Fix: utilize [programmatic generation](https://github.com/vega/ts-json-schema-generator#programmatic-usage) of the schema

**Comment by PythonCreator27** [comment]
Yeah... this has been the case for a while. I used to use WSL to get around it, but as new contributors come, WSL won't be the best solution. We can't tell everybody to install something new just to contribute. I was thinking about this today, and you just filed the bug for it. This is definitely a possible thing, and using .js over .sh would be preferred, since not everyone has git bash or WSL installed. @Sciguymjm Thanks for filing this (you saved me like 10 minutes)! I'll see if I can fix this tommorow.

**Comment by gadicc** [comment]
Hey @Sciguymjm and @PythonCreator27, thank you both for this.  Absolutely want contributing to be easier from Windows so thanks for raising these issues that I'd totally not be aware of otherwise.

@Sciguymjm, I agree that programmatic generation of the schema is the way to go.  Let's see when I get a chance for this, as ideally I'd like to merge the "schema-tweak" code together too.  @PythonCreator27 please also let me know if you've started on this and what approach you're taking.
