### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module' when using browserify 

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [gadicc/node-yahoo-finance2#266]
I'm trying to create a user input where the user can choose a stock Symbol, a Start Date, End Date and Interval. I would then like for this information to be passed along the javascript function api to retrieve information about that specific stock such as open, high, low, close, etc. The javascript function is working and I'm being able to save the data as csv files as well and I want to use browserify (by running npm run build) to create a bundle.js so I can use HTML (since we can't use import or require() with the browser), but I keep getting this error when creating the bundle.js file.

## Javascript code

```
const ObjectsToCsv = require('objects-to-csv');
const yahooFinance = require('yahoo-finance2').default; // NOTE the .default


let symbolNew = document.getElementById("symbol").value;
let periodStart = document.getElementById("period1").value;
let periodEnd = document.getElementById("period2").value;
let intervalNew = document.getElementById("interval").value;

async function api(symbol, start, end, val) {
  const query = String(symbol);
  const queryOptions = { period1: new Date(start), period2: new Date(end), interval: String(val) };
  let result = await yahooFinance.historical(query, queryOptions);
  let resultWithSymbol = result.map((item) => ({ ...item, symbol: query }));

  console.log(resultWithSymbol);
  return resultWithSymbol;

};
api(symbolNew, periodStart, periodEnd, intervalNew);
```
 

## Error Message

```
C:\Users\Rafael Oliveira\Desktop\teste\node_modules\yahoo-finance2\dist\esm\src\index-browser.js:1
import yahooFinance from "./index-common.js";
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api@1.0.0 build: `browserify api.js -o bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the api@1.0.0 build script.
```

## Environment, package.json and eslint configuration
```
{
  "name": "api",
  "version": "1.0.0",
  "type": "commonjs",
  "main": "api.js",
  "dependencies": {
    "d3": "^7.0.0",
    "objects-to-csv": "^1.3.6",
    "yahoo-finance2": "^1.14.3"
  },
  "devDependencies": {
    "@babel/core": "^7.15.0",
    "browserify": "^17.0.0",
    "eslint": "^7.32.0",
    "eslint-config-google": "^0.14.0",
    "watchify": "^4.0.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "browserify api.js -o bundle.js",
    "watch": "watchify api.js -o bundle.js"

  },
  "author": "",
  "license": "ISC",
  "description": ""
}
```
```
module.exports = {
  env: {
    browser: true,
    es2021: true,
    node: true
  },
  extends: [
    'standard'
  ],
  parserOptions: {
    ecmaVersion: 12,
    sourceType: 'module'
  },
  rules: {
  }
}

```

I have sourceType = module and type = commonjs so I can read the "require()" function on javascript. I should be able to use browserify to create a bundle and retrieve the input from the html, but I keep getting the error "import yhaooFinance from "./index-common.js". Does this mean I can't use browserify and I must change type = module in my package.json? And does it also mean I need to use bable instead?

Thank you in advance!

**Comment by gadicc** [comment]
Hey @Rafael-Silva-Oliveira.

Unfortunately I don't have any experience with browserify.  I did a quick Google and perhaps tools like [esmify](https://github.com/mattdesl/esmify) or [babelify](https://github.com/babel/babelify) *may* help.

Possibly you're running into this problem because we (in yahoo-finance2) specify esm for the browser.  But that's because actually modern browsers today can handle esm (and import) pretty well without any transforms.  (As a quick hack, I guess you could also edit `node_modules/yahoo-fiannce2/package.json` and change the `browser` line from `./dist/esm/...` to `./dist/cjs/...` but it will break every time you upgrade the package).

Babel may indeed handle this case better... certainly our users using e.g. `create-react-app` (which uses webpack + babel) aren't having any issues.  Same codesandbox which I believe uses [parcel](https://parceljs.org/).

Note however that using yahoo-finance in the browser is much more complicated than in node, since the browser will block requests to Yahoo's servers due to Yahoo's CORS policy (there's a note about this in the README).
