### ISSUE TITLE
[quote] Throws on quoteType "NONE" (e.g. SRNG)

### ISSUE THREAD

**Issue by gadicc** [gadicc/node-yahoo-finance2#381]
As reported by @glintik in https://github.com/gadicc/node-yahoo-finance2/issues/376#issuecomment-1013663952:

```js
let quote = await yahooFinance.quote('SRNG');
```

throws because the data is:

```js
{
      language: 'en-US',
      region: 'US',
      quoteType: 'NONE',
      triggerable: false,
      messageBoardId: 'finmb_130407341',
      esgPopulated: false,
      tradeable: false,
      symbol: 'SRNG'
}
```

and we've never encountered a quoteType of `NONE` before :laughing: 

Background (again, from @glintik in same comment):

> Some details about SRNG:
> It's SPAC company that was used by Ginkgo Bioworks to be listed on NYSE. Just after SPAC deal, SRNG renamed to DNA.

**Comment by glintik** [comment]
Even more details :).

**DM**(NYSE) has completed its acquisition of **XONE**(NASDAQ) and the latter was delisted on November 12, 2021.
Response for quote() is very similar:
```
{
  "language": "en-US",
  "region": "US",
  "quoteType": "NONE",
  "triggerable": false,
  "messageBoardId": "finmb_225890957",
  "esgPopulated": false,
  "tradeable": false,
  "symbol": "XONE"
}
```

**WORK**(NYSE) was acquired by **CRM**(NYSE) and was delisted on July 22, 2021.
Response for quote() is `undefined`, that's an expected behaviour.

Btw, `_chart()` returns `No data found, symbol may be delisted` and `historical()` returns `HTTPError: Not Found` for valid period when stocks were not delisted yet. I think this information may be considered to include in the main README file to prevent various bugs.

**Comment by gadicc** [comment]
Hey @glintik, thanks for your patience and all the extra info.

I'm still not sure what to do this and would love your input...  my current thinking is actually to just return `undefined` for `"NONE"` quotes, to keep things consistent... since I can't imagine anyone will ever use the yahoo `messageBoardId`.  But I guess if I'm silently dropping data, I should add an option to NOT do this too.  What do you think?

And thanks for your very helpful comments re `_chart()` and `historical()`, I'll add some notes for that.

**Comment by glintik** [comment]
>  just return undefined for "NONE" quotes, to keep things consistent
Agree, undefined is expected for such queries. Unfortunately, all current and historic ticker information becomes unavailable in case of delisting. Thank you for adding notes to documentation, this is very important for software business logic.
