### ISSUE TITLE
Failed validation: #/definitions/QuoteSummaryResult: 

### ISSUE THREAD

**Issue by martincsl** [gadicc/node-yahoo-finance2#734]
# Validation Error

## Minimal Reproduction
 await yahooFinance.quoteSummary('PLTR', { modules: [ "incomeStatementHistory" ] });

## Symbol(s) that it happened for
- JPM
- CVX
- AAPL

## Error Message
	"error": "Failed Yahoo Schema validation"
```

```

## Environment
Browser or Node: Node
Node version (if applicable): v16.13.0
Npm version: 
Browser version (if applicable):
Library version (e.g. `1.10.1`):

**Comment by martincsl** [comment]
hello friends, do you know if yahoo finance change the structure? This error is happening under the QuoteSummay.  Quote seems to working poperly. 
I've been using wait yahooFinance.quoteSummary('PLTR', { modules: [ "incomeStatementHistory" ] }) for some time with any problem. But now i'm receiving this error message: "error": "Failed Yahoo Schema validation".

Thanks in advance!

**Comment by gadicc** [comment]
Thanks @martincsl, for reporting.

Yes, Yahoo do occasionally change their output, which is why we need to watch it so carefully, to ensure the library gives a catchable error before returning you a new kind of data structure which can completely break your app / code / db :D

So, thanks for reporting.  This has been fixed and will be in the next release.  There'll be an automatic message here when that happens.
