### ISSUE TITLE
Node v22.8.0 : SyntaxError: Unexpected identifier 'assert'

### ISSUE THREAD

**Issue by eduwass** [gadicc/node-yahoo-finance2#800]
# Bug Report

## Describe the bug
On:
```
✦ ❯ node -v
v22.8.0
``` 

Getting an error when trying to execute, eg:

```
✦ ❯ npx yahoo-finance2 search AAPL
file:///Users/eduwass/.npm/_npx/2b336743dcaf6c17/node_modules/yahoo-finance2/dist/esm/src/lib/yahooFinanceFetch.js:5
import pkg from "../../package.json" assert { type: "json" };
                                     ^^^^^^

SyntaxError: Unexpected identifier 'assert'
    at compileSourceTextModule (node:internal/modules/esm/utils:337:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:166:18)
    at callTranslator (node:internal/modules/esm/loader:436:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:442:30)

Node.js v22.8.0
``` 

## Minimal Reproduction
1. Environment with Node v22.8.0
2. Try to run: `npx yahoo-finance2 search AAPL`

## Environment
Browser or Node: node
Node version: v22.8.0
Npm version: 10.8.3
Library version: yahoo-finance2@2.12.4

**Comment by eduwass** [comment]
PS: Whoops, I just realized that the library supports Node LTS and that version is currently v20.17.0 so feel free to disregard

**Comment by gadicc** [comment]
Hey @eduwass, thanks for the report.  We support LTS but we'd like to support latest versions too.  So I'm going to re-open for discoverability.  Unfortunately though this is a rare case of not being able to support both simultaneously.

The issue here is [import assertions / attributes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import/with), which was an important development to make imports safer.  Unfortunately, the roll out wasn't great, because, there were times when certain node verisons would fail WITH it and other versions fail WITHOUT it at the same time.  To make things worse, the syntax changed from `assert` to `with`, and created a similar problem for a second time.

This is really unfortunate as usually the node team plans these things a bit better to avoid these kinds of mutually exclusive support situations.  If memory serves, current Node LTS is v18, and `with` is supported from `v18.2` or so.  Currently we support 18.0+, but, at some point in the future, we'll bump the minimum supported version to 18.2+, and then can switch to `with`, and newer versions will work.  So, leaving this open for those who want a notification when that happens.

**Comment by kwo** [comment]
I am experiencing the same issue. v22 is scheduled to become LTS next month. https://github.com/nodejs/release#release-schedule

**Comment by kwo** [comment]
I'm experiencing the same issue. The current LTS is v20. v22 is scheduled to become LTS next month. https://github.com/nodejs/release#release-schedule

**Comment by kwo** [comment]
Thanks! Wow, I was not expecting such a quick turnaround. You're awesome man!

**Comment by eduwass** [comment]
Awesome, thanks for your work @gadicc ! 👏

**Comment by gadicc** [comment]
Thanks @kwo and @eduwass! :pray:
