### ISSUE TITLE
Failed to get crumb, status 404, statusText: Not Found

### ISSUE THREAD

**Issue by ionescu-valentin** [gadicc/node-yahoo-finance2#835]
# Bug Report

## Describe the bug
I'm receiving the `Failed to get crumb, status 404, statusText: Not Found` error when calling quote on any symbol. 
![image](https://github.com/user-attachments/assets/47d06029-1b02-4f86-9b24-441c73d322e0)

## Minimal Reproduction
`await yahooFinance.quote('AAPL')`

## Environment
Browser or Node: Node
Node version: 20.15.1
Npm version: 10.8.3
Library version : 2.13.2

## Additional Context
This started yesterday evening, and it's only happening on a server that's running on render. It works fine when running the code locally.
I updated the library to the latest version but the issue still persists.

**Comment by ionescu-valentin** [comment]
Update: It got fixed by itself one day later. Still not sure if it's stable.

**Comment by gadicc** [comment]
Thanks @ionescu-valentin for reporting and for your follow up and patience.  Yes, unfortunately these kind of transient issues do pop up from time to time on Yahoo's servers, and there's not much we can do about it, but as you saw, they do eventually resolve themselves within a few hours to a day.

The best you can do as a user is try/catch the yahoo-finance call, which is a good practice anyway since a number of unexpected things can occasionally come up as mentioned in the docs.

As for why it worked locally but not on your server, these issues are usually bad cache results on yahoo's CDN, or code rollout to their edge network, so, are usually limited to a very small geographical region.

Happy holidays!
