### ISSUE TITLE
Use both `query1` and `query2`.

### ISSUE THREAD

**Issue by gadicc** [gadicc/node-yahoo-finance2#95]
As noted by @PythonCreator27 in https://github.com/gadicc/node-yahoo-finance2/issues/8#issuecomment-802463467, both hostnames above may be used interchangeably.

I took a quick look at https://finance.yahoo.com/, and in the source we have:

```js
root.App.main = {
  "context": {
    // ...
    "plugins": {
      // ...
      "ServicePlugin": {
        "configs": {
          "tachyon": {
            "defaults": {
              "withCredentials": true,
              "timeout": 4000,
              "protocol": "http",
              "host": "iquery.finance.yahoo.com:4080",
              "proxyFallback": "\u002F__query",
              "client": {
                "protocol": "https",
                "host": ["query1.finance.yahoo.com", "query2.finance.yahoo.com"]
              }
            }
          }
        }
      }
      // ...
    }
    // ...
  }
}
```

My current thinking:

* Super short term: not urgent at all, everything works as is (and has for like 10 years I guess)
* Shortish term: could assume both hostnames above and randomly pick one at query time
* Longer term: if request for one host name fails, could try the other
* Longest term: if both fail, check the main html above if there are any updates (I definitely wouldn't do this on every request, and even "on first request" is not ideal on serverless setups, but could be behind an option - still, don't think it's worth the wasted time on the extra request until we have good reason).

**Comment by PythonCreator27** [comment]
This is going to require a good bit of breaking changes and refactoring...
1. We will have to add options to `_moduleExec` so that it can tell whether the module uses the `query#` endpoints or not.
2. We will then have to change the hosts dynamically, calling for a `_moduleExec` wrapper, made for modules using the `query#` endpoints.

My suggestion:
- Short term: Unify what we use in our code at first (probably `query1`), so that we have some sort of unity in our code. 
- Long term: 
   - Add logic for checking if the first failed and trying again with `query2` and `iquery`. 
   - Also send an error report to some server. 
     Example format:
     ```json
     {
         "host": "query1",
         "module": "quote",
     }
     ```
   - If everything fails, throw an error.

We probably don't want to be too dynamic and start checking the HTML. Then we would check the HTML on every request, and that could pile up fast and slow down programs. Even if we did request and cache the new host(s), we would have to cache it somewhere. In node, we would probably use the filesystem, but in the browser, we would use localStorage. Changing between them, preventing errors, etc. would not be worth the cost.

Ideally, people should just file issues and we should fix the problem.

**Comment by PythonCreator27** [comment]
@gadicc This is going to require a good bit of breaking changes and refactoring...
1. Options will have to be added to `_moduleExec` so that it can tell whether the module uses the `query#` endpoints or not.
2. Hosts will have to be changed dynamically, calling for a `_moduleExec` wrapper, made for modules using the `query#` endpoints.
3. We are going to have to check whether errors are coming from validation or from the API and handle them accordingly.

Through all of it, we are going to have to make sure that we don't mess up modules like `autoc` that don't use the `query#` endpoints.

My suggestion:
- Short term: Unify what we use in our code at first (probably `query1`), so that we have some sort of unity in our code. 
- Long term: 
   - Add logic for checking if the first failed and trying again with `query2` and `iquery`. 
   - Also send an error report to some server. 
     Example format:
     ```json5
     {
         "host": "query1",
         "module": "quote",
         "symbol": "AMZN",
         "queryOptions": {
             // Query options here
         }
         "result": {
             // Will have real result/response here
         },
         "errorStatus": "401"
     }
     ```
   - If everything fails, throw an error and file an issue through the GitHub API.

We probably don't want to be too dynamic and start checking the HTML. Then we would check the HTML on every request, and that could pile up fast and slow down programs. Even if we did request and cache the new host(s), we would have to cache it somewhere. In node, we would probably use the filesystem, but in the browser, we would use `localStorage`. Changing between them, preventing ReferenceErrors, etc. would not be worth the cost. Ideally, people should just file issues and the problem should fixed like normal. 

In the end, it is quite unlikely that yahoo will change the domain endpoints. So overall, I think the approach stated above should work well. Again, @gadicc, as you said, things have been working the way that they are for 10 years, so I would take this as a low priority issue.

**Comment by PythonCreator27** [comment]
@gadicc This is going to require a good bit of breaking changes and refactoring...
1. Options will have to be added to `_moduleExec` so that it can tell whether the module uses the `query#` endpoints or not.
2. Hosts will have to be changed dynamically, calling for a `_moduleExec` wrapper, made for modules using the `query#` endpoints.
3. We are going to have to check whether errors are coming from validation or from the API and handle them accordingly.
4. A new major version will have to be released, as we are changing the behavior of the library (trying again instead of failing).

Through all of it, we are going to have to make sure that we don't mess up modules like `autoc` that don't use the `query#` endpoints.

My suggestion:
- Short term: Unify what we use in our code at first (probably `query1`), so that we have some sort of unity in our code. 
- Long term: 
   - Add logic for checking if the first failed and trying again with `query2` and `iquery`. 
   - Also send an error report to some server. 
     Example format:
     ```json5
     {
         "host": "query1",
         "module": "quote",
         "symbol": "AMZN",
         "queryOptions": {
             // Query options here
         }
         "result": {
             // Will have real result/response here
         },
         "errorStatus": "401"
     }
     ```
   - If everything fails, throw an error and file an issue through the GitHub API.

We probably don't want to be too dynamic and start checking the HTML. Then we would check the HTML on every request, and that could pile up fast and slow down programs. Even if we did request and cache the new host(s), we would have to cache it somewhere. In node, we would probably use the filesystem, but in the browser, we would use `localStorage`. Changing between them, preventing ReferenceErrors, etc. would not be worth the cost. Ideally, people should just file issues and the problem should fixed like normal. 

In the end, it is quite unlikely that yahoo will change the domain endpoints. So overall, I think the approach stated above should work well. Again, @gadicc, as you said, things have been working the way that they are for 10 years, so I would take this as a low priority issue.
